Repository scanapi/scanapi, pull requests merged in 2019-11, with the labels that each got.

#56 Refactor docs_write.py (now reporter.py)
  .gitignore
  README.md
  examples/cat_api/.scanapi.yaml
  examples/json_place_holder/.scanapi.yaml
  examples/open_weather_map/.scanapi.yaml
  requirements.txt
  scanapi/__init__.py
  scanapi/docs_writer.py
  scanapi/reporter.py
  scanapi/settings.py
  scanapi/templates/console.jinja
  scanapi/templates/html.jinja
  scanapi/templates/markdown.jinja
  setup.py
Labels: code quality, feature, reporter

#65 New overview image
  README.md
  images/overview.png
Labels: documentation

#67 Refactor on variables evaluation
  scanapi/__init__.py
  scanapi/requests_maker.py
  scanapi/spec_evaluator.py
  scanapi/tree/api_node.py
  scanapi/tree/api_tree.py
  scanapi/tree/endpoint_node.py
  scanapi/tree/request_node.py
  scanapi/tree/root_node.py
  scanapi/variable_parser.py
  tests/functional/step_defs/test_call_requests.py
  tests/unit/test_spec_evaluator.py
  tests/unit/test_variable_parser.py
  tests/unit/tree/test_api_node.py
  tests/unit/tree/test_api_tree.py
Labels: refactor

#68 Refactor on Evaluators
  README.md
  scanapi/evaluators/code_evaluator.py
  scanapi/evaluators/spec_evaluator.py
  scanapi/evaluators/string_evaluator.py
  scanapi/tree/api_tree.py
  scanapi/tree/tree_keys.py
  tests/unit/evaluators/test_code_evaluator.py
  tests/unit/evaluators/test_spec_evaluator.py
  tests/unit/evaluators/test_string_evaluator.py
  tests/unit/test_spec_evaluator.py
Labels: refactor
